# Generated by Django 2.1.5 on 2019-05-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biddalo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
